import Reveal from "reveal.js";
import "reveal.js/reveal.css";
import "./styles/slides.css";
import { READING_THEME_IDS, READING_THEMES } from "./theme-data";
import { initCalloutFold } from "./stacked-pages";
import { initMath } from "./math-init";
import { initMermaid } from "./mermaid-init";
import { initIcons } from "./icons";

type RevealConfig = Record<string, boolean | number | string>;
type SplitPolicy = "auto" | "chapters" | "sections" | "detail" | "fit" | "explicit" | "single";
type Aspect = "fit" | "21:9" | "16:10" | "16:9" | "3:2" | "4:3" | "1:1" | "custom";
type Tool = "laser" | "magnify" | "pen" | null;
type Panel = "settings" | "tools" | "picker" | "timer" | "help" | "grid" | null;

interface SlideSettings extends RevealConfig { theme: string; codeWrap: boolean; split: SplitPolicy; }
interface StoredPreferences { theme?: string; transition?: string; codeWrap?: boolean; textScale?: number; aspect?: Aspect; customRatio?: string; center?: boolean; progress?: boolean; slideNumber?: boolean; reducedMotion?: boolean; }
interface Point { x: number; y: number; }
interface Stroke { color: string; width: number; points: Point[]; }

const SETTINGS_KEY = "vaultpub.slideSettings.v2";
const LEGACY_SETTINGS_KEY = "vaultpub.slideSettings.v1";
const SPLIT_COOKIE = "vaultpub_slide_split";
const SPLIT_OPTIONS: Array<[SplitPolicy, string]> = [["auto", "Auto"], ["chapters", "Chapters"], ["sections", "Sections"], ["detail", "Detail"], ["fit", "Fit viewport"], ["explicit", "Explicit"], ["single", "Single"]];
const ASPECT_OPTIONS: Array<[Aspect, string]> = [["fit", "Fit available space"], ["21:9", "21:9"], ["16:10", "16:10"], ["16:9", "16:9"], ["3:2", "3:2"], ["4:3", "4:3"], ["1:1", "1:1"], ["custom", "Custom"]];
const TRANSITIONS = ["none", "fade", "slide", "convex", "concave", "zoom"];

function readJson<T>(id: string, fallback: T): T { try { return JSON.parse(document.getElementById(id)?.textContent || "") as T; } catch { return fallback; } }
function text(value: string | null | undefined): string { return value?.trim() || "Untitled slide"; }
function ratio(value: string): number | null { const parts = value.trim().split(":"); const number = parts.length === 2 ? Number(parts[0]) / Number(parts[1]) : Number(value); return Number.isFinite(number) && number > 0.1 && number < 10 ? number : null; }
function options(values: Array<[string, string]>, selected: string): string { return values.map(([value, label]) => `<option value="${value}"${value === selected ? " selected" : ""}>${label}</option>`).join(""); }
function swatches(colors: string[]): string { return colors.map((color) => `<span style="background:${color}"></span>`).join(""); }

function readStored(): StoredPreferences {
  try {
    const raw = JSON.parse(localStorage.getItem(SETTINGS_KEY) || localStorage.getItem(LEGACY_SETTINGS_KEY) || "{}") as Record<string, unknown>;
    if (!raw || typeof raw !== "object" || Array.isArray(raw)) return {};
    return {
      theme: typeof raw.theme === "string" && READING_THEME_IDS.has(raw.theme) ? raw.theme : undefined,
      transition: typeof raw.transition === "string" && TRANSITIONS.includes(raw.transition) ? raw.transition : undefined,
      codeWrap: typeof raw.codeWrap === "boolean" ? raw.codeWrap : undefined,
      textScale: typeof raw.textScale === "number" && raw.textScale >= 75 && raw.textScale <= 300 && raw.textScale % 5 === 0 ? raw.textScale : undefined,
      aspect: typeof raw.aspect === "string" && ASPECT_OPTIONS.some(([id]) => id === raw.aspect) ? raw.aspect as Aspect : undefined,
      customRatio: typeof raw.customRatio === "string" && ratio(raw.customRatio) ? raw.customRatio : undefined,
      center: typeof raw.center === "boolean" ? raw.center : undefined,
      progress: typeof raw.progress === "boolean" ? raw.progress : undefined,
      slideNumber: typeof raw.slideNumber === "boolean" ? raw.slideNumber : undefined,
      reducedMotion: typeof raw.reducedMotion === "boolean" ? raw.reducedMotion : undefined,
    };
  } catch { return {}; }
}
function saveStored(preferences: StoredPreferences): void { try { localStorage.setItem(SETTINGS_KEY, JSON.stringify(preferences)); } catch { /* storage is optional */ } }
function setSplitCookie(value: SplitPolicy | null): void { document.cookie = value ? `${SPLIT_COOKIE}=${encodeURIComponent(value)}; max-age=31536000; path=/; SameSite=Lax` : `${SPLIT_COOKIE}=; max-age=0; path=/; SameSite=Lax`; }

function buildInterface(defaults: SlideSettings, preferences: StoredPreferences): HTMLElement {
  const selectedTheme = preferences.theme || defaults.theme;
  const selectedTransition = preferences.transition || String(defaults.transition || "slide");
  const selectedAspect = preferences.aspect || "fit";
  const themeCards = READING_THEMES.map((theme) => `<button type="button" class="slides-theme-choice${theme.id === selectedTheme ? " is-selected" : ""}" data-theme="${theme.id}" aria-label="${theme.name}" aria-pressed="${theme.id === selectedTheme}"><span class="slides-theme-swatch">${swatches(theme.preview)}</span><span>${theme.name}</span></button>`).join("");
  const splitChoices = SPLIT_OPTIONS.map(([value, label]) => `<button type="button" class="slides-choice${value === defaults.split ? " is-selected" : ""}" data-split="${value}" aria-pressed="${value === defaults.split}">${label}</button>`).join("");
  const root = document.createElement("div");
  root.className = "slides-ui";
  root.innerHTML = `
    <div class="slides-toast" role="status" aria-live="polite"></div><canvas class="slides-ink" aria-label="Drawing canvas"></canvas><div class="slides-laser" aria-hidden="true"></div>
    <nav class="slides-dock" aria-label="Presentation controls">
      <a class="slides-ui-button" data-return-control><i data-lucide="arrow-left" aria-hidden="true"></i></a>
      <button class="slides-ui-button" type="button" data-action="previous" data-tooltip="Previous slide" aria-label="Previous slide"><i data-lucide="chevron-left" aria-hidden="true"></i></button>
      <button class="slides-ui-button slides-counter" type="button" data-action="picker" data-tooltip="Jump to a slide" aria-label="Jump to a slide">0 / 0</button>
      <button class="slides-ui-button" type="button" data-action="next" data-tooltip="Next slide" aria-label="Next slide"><i data-lucide="chevron-right" aria-hidden="true"></i></button>
      <button class="slides-ui-button" type="button" data-action="overview" data-tooltip="Slide grid" aria-label="Slide grid"><i data-lucide="layout-grid" aria-hidden="true"></i></button>
      <button class="slides-ui-button" type="button" data-action="settings" data-tooltip="Slide settings" aria-label="Slide settings" aria-expanded="false"><i data-lucide="settings-2" aria-hidden="true"></i></button>
      <span class="slides-dock-divider" aria-hidden="true"></span>
      <button class="slides-ui-button" type="button" data-action="fullscreen" data-tooltip="Fullscreen" aria-label="Fullscreen"><i data-lucide="maximize" aria-hidden="true"></i></button>
      <button class="slides-ui-button" type="button" data-tool="laser" data-tooltip="Laser pointer" aria-label="Laser pointer" aria-pressed="false"><i data-lucide="circle-dot" aria-hidden="true"></i></button>
      <button class="slides-ui-button" type="button" data-tool="magnify" data-tooltip="Magnify" aria-label="Magnify" aria-pressed="false"><i data-lucide="zoom-in" aria-hidden="true"></i></button>
      <button class="slides-ui-button" type="button" data-tool="pen" data-tooltip="Draw" aria-label="Draw" aria-pressed="false"><i data-lucide="pen-line" aria-hidden="true"></i></button>
      <button class="slides-ui-button slides-timer-display" type="button" data-action="timer" data-tooltip="Presentation timer" aria-label="Presentation timer">00:00</button>
      <button class="slides-ui-button" type="button" data-action="blackout" data-tooltip="Blackout" aria-label="Blackout"><i data-lucide="monitor-off" aria-hidden="true"></i></button>
      <button class="slides-ui-button" type="button" data-action="help" data-tooltip="Keyboard shortcuts" aria-label="Keyboard shortcuts"><i data-lucide="circle-help" aria-hidden="true"></i></button>
    </nav>
    <section class="slides-panel slides-settings-panel" hidden aria-label="Slide settings" tabindex="-1"><header><strong>Slide settings</strong><button type="button" data-action="close" aria-label="Close settings">×</button></header><div class="slides-settings-grid">
      <div class="slides-settings-group slides-theme-group"><label>Theme</label><div class="slides-theme-cards">${themeCards}</div></div>
      <div class="slides-settings-group"><label>Transition<select data-setting="transition">${options(TRANSITIONS.map((item) => [item, item] as [string, string]), selectedTransition)}</select></label><label>Aspect ratio<select data-setting="aspect">${options(ASPECT_OPTIONS, selectedAspect)}</select></label><label class="slides-custom-ratio" ${selectedAspect === "custom" ? "" : "hidden"}>Custom ratio<input data-setting="customRatio" value="${preferences.customRatio || ""}" placeholder="1920:1080"></label><label>Text size<span class="slides-range"><input data-setting="textScale" type="range" min="75" max="300" step="5" value="${preferences.textScale || 100}"><output data-output="textScale">${preferences.textScale || 100}%</output></span></label></div>
      <div class="slides-settings-group slides-split-group"><label>Split slides</label><div class="slides-split-choices">${splitChoices}</div></div>
      <div class="slides-settings-group slides-switches"><label><input data-setting="codeWrap" type="checkbox"> Wrap code</label><label><input data-setting="center" type="checkbox"> Vertically center</label><label><input data-setting="progress" type="checkbox"> Progress bar</label><label><input data-setting="slideNumber" type="checkbox"> Slide number</label><label><input data-setting="reducedMotion" type="checkbox"> Reduce motion</label><button type="button" data-action="reset">Reset defaults</button></div>
    </div></section>
    <section class="slides-panel slides-tools-panel" hidden aria-label="Drawing tools" tabindex="-1"><header><strong>Draw</strong><button type="button" data-action="close" aria-label="Close drawing tools">×</button></header><div class="slides-ink-colors">${["#ef4444", "#facc15", "#3b82f6", "#111827"].map((color, index) => `<button type="button" data-ink-color="${color}" class="${index === 0 ? "is-selected" : ""}" style="--ink-color:${color}" aria-label="Select ink colour"></button>`).join("")}</div><label>Width <span class="slides-range"><input data-setting="inkWidth" type="range" min="2" max="16" value="4"></span></label><div class="slides-panel-row"><button data-action="eraser">Eraser</button><button data-action="undo">Undo</button><button data-action="redo">Redo</button><button data-action="clear">Clear</button></div></section>
    <section class="slides-panel slides-picker-panel" hidden aria-label="Slide chooser" tabindex="-1"><header><strong>Jump to slide</strong><button data-action="close" aria-label="Close slide chooser">×</button></header><input data-action="search" type="search" placeholder="Search slide titles"><div class="slides-picker-list" role="listbox"></div></section>
    <section class="slides-panel slides-timer-panel" hidden aria-label="Presentation timer" tabindex="-1"><header><strong>Timer</strong><button data-action="close" aria-label="Close timer">×</button></header><div class="slides-clock"></div><div class="slides-panel-row"><button data-action="timer-start">Start</button><button data-action="timer-pause">Pause</button><button data-action="timer-reset">Reset</button></div></section>
    <section class="slides-panel slides-help-panel" hidden aria-label="Keyboard shortcuts" tabindex="-1"><header><strong>Keyboard shortcuts</strong><button data-action="close" aria-label="Close keyboard shortcuts">×</button></header><p>Arrows/Space navigate. G chooser. F fullscreen. L laser. Z magnify. D draw. B blackout. Esc closes a panel or tool.</p></section>
    <section class="slides-grid" hidden aria-label="Slide grid" tabindex="-1"><header><strong>Slide grid</strong><button data-action="close" aria-label="Close slide grid">×</button></header><div class="slides-grid-list"></div></section>`;
  const returnControl = root.querySelector<HTMLAnchorElement>("[data-return-control]")!;
  returnControl.href = document.body.dataset.returnUrl || "/";
  returnControl.dataset.tooltip = document.body.dataset.returnLabel || "Return";
  returnControl.setAttribute("aria-label", document.body.dataset.returnLabel || "Return");
  for (const setting of ["codeWrap", "center", "progress", "slideNumber", "reducedMotion"] as const) root.querySelector<HTMLInputElement>(`[data-setting="${setting}"]`)!.checked = preferences[setting] ?? (setting === "reducedMotion" ? matchMedia("(prefers-reduced-motion: reduce)").matches : Boolean(defaults[setting]));
  return root;
}

document.addEventListener("DOMContentLoaded", () => {
  const revealElement = document.querySelector<HTMLElement>(".reveal");
  if (!revealElement) return;
  const defaults = readJson<SlideSettings>("vaultpub-slide-settings", { theme: "light", codeWrap: true, split: "auto" });
  const deck = new Reveal(revealElement, { ...readJson<RevealConfig>("vaultpub-slides-config", {}), controls: false }) as any;
  void deck.initialize().then(() => {
    initCalloutFold(); initMermaid(); initMath(); void import("./code-highlight?slides").then((module) => (module as unknown as typeof import("./code-highlight")).initCodeHighlight());
    const ui = buildInterface(defaults, readStored()); document.body.appendChild(ui); initIcons();
    const dock = ui.querySelector<HTMLElement>(".slides-dock")!;
    const panels = new Map<Exclude<Panel, null>, HTMLElement>([["settings", ui.querySelector(".slides-settings-panel")!], ["tools", ui.querySelector(".slides-tools-panel")!], ["picker", ui.querySelector(".slides-picker-panel")!], ["timer", ui.querySelector(".slides-timer-panel")!], ["help", ui.querySelector(".slides-help-panel")!], ["grid", ui.querySelector(".slides-grid")!]]);
    const canvas = ui.querySelector<HTMLCanvasElement>(".slides-ink")!; const context = canvas.getContext("2d")!; const laser = ui.querySelector<HTMLElement>(".slides-laser")!; const toast = ui.querySelector<HTMLElement>(".slides-toast")!; const counter = ui.querySelector<HTMLElement>(".slides-counter")!; const picker = ui.querySelector<HTMLElement>(".slides-picker-list")!; const gridList = ui.querySelector<HTMLElement>(".slides-grid-list")!;
    let activePanel: Panel = null; let trigger: HTMLElement | null = null; let tool: Tool = null; let magnified = false; let inkColor = "#ef4444"; let inkWidth = 4; let drawing = false; let stroke: Stroke | null = null; let timerStarted: number | null = null; let elapsed = 0; let idle = 0; let resizeTimer = 0; let applyingSplit = false;
    const ink = new Map<string, Stroke[]>(); const redo = new Map<string, Stroke[]>(); const originalSlides = Array.from(revealElement.querySelectorAll<HTMLElement>(".slides > section.vaultpub-slide")).map((slide) => slide.cloneNode(true) as HTMLElement);
    const key = (): string => { const index = deck.getIndices(); return `${index.h || 0}-${index.v || 0}`; };
    const strokes = (): Stroke[] => ink.get(key()) || [];
    const say = (message: string): void => { toast.textContent = message; toast.classList.add("is-visible"); window.setTimeout(() => toast.classList.remove("is-visible"), 1600); };
    const wake = (): void => { document.body.classList.remove("slides-ui-idle"); clearTimeout(idle); if (!activePanel && !dock.matches(":hover")) idle = window.setTimeout(() => document.body.classList.add("slides-ui-idle"), 2500); };
    const draw = (): void => { context.clearRect(0, 0, innerWidth, innerHeight); strokes().forEach((item) => { context.beginPath(); context.strokeStyle = item.color; context.lineWidth = item.width; context.lineCap = "round"; item.points.forEach((point, index) => index ? context.lineTo(point.x * innerWidth, point.y * innerHeight) : context.moveTo(point.x * innerWidth, point.y * innerHeight)); context.stroke(); }); };
    const sizeCanvas = (): void => { const pixel = devicePixelRatio || 1; canvas.width = innerWidth * pixel; canvas.height = innerHeight * pixel; canvas.style.width = `${innerWidth}px`; canvas.style.height = `${innerHeight}px`; context.setTransform(pixel, 0, 0, pixel, 0, 0); draw(); };
    const saved = (): StoredPreferences => readStored();
    const dimensions = (): { width: number; height: number } => { const preference = saved(); const chosen = preference.aspect || "fit"; if (chosen === "fit") return { width: innerWidth, height: innerHeight }; const value = chosen === "custom" ? ratio(preference.customRatio || "") : ratio(chosen); const safe = value || 16 / 9; return { width: 1600, height: Math.round(1600 / safe) }; };
    const isFit = (): boolean => defaults.split === "fit";
    const panelClose = (): void => { if (!activePanel) return; panels.get(activePanel)!.hidden = true; activePanel = null; document.body.classList.remove("slides-panel-open"); dock.querySelectorAll<HTMLElement>("[aria-expanded]").forEach((button) => button.setAttribute("aria-expanded", "false")); const previous = trigger; trigger = null; previous?.focus(); wake(); };
    const panelOpen = (next: Exclude<Panel, null>, source: HTMLElement): void => { if (activePanel === next) { panelClose(); return; } panels.forEach((panel) => panel.hidden = true); activePanel = next; trigger = source; panels.get(next)!.hidden = false; document.body.classList.add("slides-panel-open"); dock.querySelectorAll<HTMLElement>("[aria-expanded]").forEach((button) => button.setAttribute("aria-expanded", String(button.dataset.action === next))); wake(); panels.get(next)!.focus(); };
    const setTool = (next: Tool): void => { if (magnified) { document.body.classList.remove("slides-magnified"); magnified = false; } tool = tool === next ? null : next; canvas.style.pointerEvents = tool === "pen" ? "auto" : "none"; canvas.classList.toggle("is-active", tool === "pen"); laser.classList.toggle("is-active", tool === "laser"); dock.querySelectorAll<HTMLElement>("[data-tool]").forEach((button) => { const selected = button.dataset.tool === tool; button.classList.toggle("is-active", selected); button.setAttribute("aria-pressed", String(selected)); }); if (tool === "pen") panelOpen("tools", dock.querySelector<HTMLElement>("[data-tool=pen]")!); else if (activePanel === "tools") panelClose(); if (tool) say(tool === "magnify" ? "Magnifier armed" : `${tool} active`); wake(); };
    const slideIndex = (): number => Math.max(0, (deck.getSlides() as HTMLElement[]).indexOf(deck.getCurrentSlide()));
    const updateNavigation = (): void => { const slides = deck.getSlides() as HTMLElement[]; const current = slideIndex(); counter.textContent = `${current + 1} / ${slides.length}`; ui.querySelectorAll<HTMLElement>("[data-slide-index]").forEach((item) => item.classList.toggle("is-current", Number(item.dataset.slideIndex) === current)); draw(); };
    const buildNavigation = (): void => { const slides = deck.getSlides() as HTMLElement[]; picker.replaceChildren(); gridList.replaceChildren(); slides.forEach((slide, index) => { const heading = slide.dataset.slideKind === "note-divider" ? `File: ${text(slide.querySelector("h1,h2,h3")?.textContent)}` : text(slide.querySelector("h1,h2,h3")?.textContent); const path = slide.dataset.sourcePath || ""; const item = document.createElement("button"); item.type = "button"; item.dataset.slideIndex = String(index); item.dataset.search = `${heading} ${path}`; item.innerHTML = `<strong>${index + 1}. ${heading}</strong>${path ? `<small>${path}</small>` : ""}`; picker.appendChild(item); const gridItem = item.cloneNode(true) as HTMLButtonElement; const thumb = document.createElement("span"); thumb.className = "slides-grid-thumb"; const content = slide.querySelector<HTMLElement>(".vaultpub-slide-content"); if (content) thumb.appendChild(content.cloneNode(true)); gridItem.prepend(thumb); gridList.appendChild(gridItem); }); updateNavigation(); };
    const pageWith = (page: HTMLElement, candidate: HTMLElement): HTMLElement => { const trial = page.cloneNode(true) as HTMLElement; trial.querySelector<HTMLElement>(".vaultpub-slide-content")!.appendChild(candidate.cloneNode(true)); return trial; };
    const paginateFit = (): void => {
      if (!isFit()) return;
      const current = deck.getCurrentSlide() as HTMLElement | null; const currentPath = current?.dataset.sourcePath || ""; const viewport = revealElement.getBoundingClientRect(); const safeHeight = Math.max(260, viewport.height - 36);
      const measure = document.createElement("div"); measure.className = "slides-fit-measure"; measure.style.width = `${Math.max(320, viewport.width)}px`; measure.style.height = `${safeHeight}px`; document.body.appendChild(measure);
      const fits = (page: HTMLElement, scale = 1): boolean => { const trial = page.cloneNode(true) as HTMLElement; trial.querySelector<HTMLElement>(".vaultpub-slide-content")!.style.setProperty("--vaultpub-fit-scale", String(scale)); measure.replaceChildren(trial); return measure.querySelector<HTMLElement>(".vaultpub-slide-content")!.scrollHeight <= safeHeight + 1; };
      const makePage = (source: HTMLElement): HTMLElement => { const page = source.cloneNode(false) as HTMLElement; page.appendChild(source.querySelector<HTMLElement>(".vaultpub-slide-content")!.cloneNode(false)); return page; };
      const pages: HTMLElement[] = [];
      originalSlides.forEach((source) => { let page = makePage(source); let content = page.querySelector<HTMLElement>(".vaultpub-slide-content")!; const commit = (): void => { if (content.childElementCount) pages.push(page); page = makePage(source); content = page.querySelector<HTMLElement>(".vaultpub-slide-content")!; };
        for (const node of Array.from(source.querySelector<HTMLElement>(".vaultpub-slide-content")!.children)) { const candidate = node.cloneNode(true) as HTMLElement; if (fits(pageWith(page, candidate))) { content.appendChild(candidate); continue; } if (content.childElementCount) { commit(); if (fits(pageWith(page, candidate))) { content.appendChild(candidate); continue; } } if (candidate.tagName === "P" && !candidate.children.length) { const words = (candidate.textContent || "").match(/\S+\s*/g) || []; let start = 0; while (start < words.length) { let low = start + 1; let high = words.length; let best = start; while (low <= high) { const middle = Math.floor((low + high) / 2); const fragment = candidate.cloneNode(false) as HTMLElement; fragment.textContent = words.slice(start, middle).join(""); if (fits(pageWith(page, fragment))) { best = middle; low = middle + 1; } else high = middle - 1; } if (best === start) { candidate.classList.add("slides-fit-overflow"); content.appendChild(candidate); break; } const fragment = candidate.cloneNode(false) as HTMLElement; fragment.textContent = words.slice(start, best).join(""); content.appendChild(fragment); start = best; if (start < words.length) commit(); } } else { candidate.classList.add("slides-fit-overflow"); content.appendChild(candidate); commit(); } }
        commit();
      });
      pages.forEach((page) => { if (!fits(page)) return; let low = 1; let high = 1.6; for (let index = 0; index < 5; index += 1) { const middle = (low + high) / 2; if (fits(page, middle)) low = middle; else high = middle; } page.querySelector<HTMLElement>(".vaultpub-slide-content")!.style.setProperty("--vaultpub-fit-scale", low.toFixed(3)); });
      measure.remove(); revealElement.querySelector<HTMLElement>(".slides")!.replaceChildren(...pages); deck.sync(); const slides = deck.getSlides() as HTMLElement[]; deck.slide(Math.max(0, slides.findIndex((slide) => slide.dataset.sourcePath === currentPath))); initCalloutFold(); initMath(); initMermaid(); buildNavigation();
    };
    const apply = (): void => { const preference = saved(); const html = document.documentElement; html.classList.remove(...Array.from(html.classList).filter((name) => name.startsWith("theme-"))); html.classList.add(`theme-${preference.theme || defaults.theme}`); html.style.setProperty("--vaultpub-slide-scale", String((preference.textScale || 100) / 100)); document.body.classList.toggle("slides-code-wrap", preference.codeWrap ?? defaults.codeWrap); document.body.classList.toggle("slides-center-content", preference.center ?? Boolean(defaults.center)); const reduced = preference.reducedMotion ?? matchMedia("(prefers-reduced-motion: reduce)").matches; document.body.classList.toggle("slides-reduced-motion", reduced); const size = dimensions(); deck.configure({ controls: false, transition: reduced ? "none" : (preference.transition || defaults.transition), progress: preference.progress ?? defaults.progress, slideNumber: preference.slideNumber ?? defaults.slideNumber, center: preference.center ?? defaults.center, width: size.width, height: size.height }); requestAnimationFrame(() => { deck.layout(); sizeCanvas(); paginateFit(); }); };
    const tick = (): void => { const total = elapsed + (timerStarted === null ? 0 : Date.now() - timerStarted); const seconds = Math.floor(total / 1000); const label = `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`; ui.querySelector<HTMLElement>(".slides-timer-display")!.textContent = label; ui.querySelector<HTMLElement>(".slides-clock")!.textContent = `${label} · ${new Intl.DateTimeFormat(undefined, { hour: "2-digit", minute: "2-digit" }).format(new Date())}`; };
    apply(); buildNavigation(); sizeCanvas(); tick(); setInterval(tick, 1000); wake();
    dock.addEventListener("pointerenter", () => { clearTimeout(idle); document.body.classList.remove("slides-ui-idle"); }); dock.addEventListener("pointerleave", wake);
    dock.addEventListener("click", (event) => { const target = (event.target as HTMLElement).closest<HTMLElement>("[data-action],[data-tool]"); if (!target) return; const action = target.dataset.action; if (target.dataset.tool) { setTool(target.dataset.tool as Exclude<Tool, null>); return; } if (action === "previous") deck.prev(); else if (action === "next") deck.next(); else if (action === "picker") panelOpen("picker", target); else if (action === "overview") panelOpen("grid", target); else if (action === "settings") panelOpen("settings", target); else if (action === "timer") panelOpen("timer", target); else if (action === "help") panelOpen("help", target); else if (action === "blackout") { deck.togglePause(); target.classList.toggle("is-active"); } else if (action === "fullscreen") { if (document.fullscreenElement) void document.exitFullscreen(); else void document.documentElement.requestFullscreen?.().catch(() => say("Fullscreen is unavailable")); } wake(); });
    ui.addEventListener("click", (event) => { const target = (event.target as HTMLElement).closest<HTMLElement>("[data-action],[data-theme],[data-split],[data-ink-color],[data-slide-index]"); if (!target || dock.contains(target)) return; const action = target.dataset.action; if (action === "close") { panelClose(); return; } if (target.dataset.slideIndex !== undefined) { deck.slide(Number(target.dataset.slideIndex)); panelClose(); return; } if (action === "reset") { localStorage.removeItem(SETTINGS_KEY); setSplitCookie(null); const url = new URL(location.href); url.searchParams.delete("split"); location.assign(url.toString()); return; } if (action === "timer-start") { if (timerStarted === null) timerStarted = Date.now(); } else if (action === "timer-pause") { if (timerStarted !== null) { elapsed += Date.now() - timerStarted; timerStarted = null; } } else if (action === "timer-reset") { elapsed = 0; timerStarted = null; } else if (action === "eraser" || action === "undo") { const current = strokes(); if (current.length) { const removed = current[current.length - 1]; ink.set(key(), current.slice(0, -1)); redo.set(key(), [...(redo.get(key()) || []), removed]); draw(); } } else if (action === "redo") { const undone = redo.get(key()) || []; const restored = undone.pop(); if (restored) { redo.set(key(), undone); ink.set(key(), [...strokes(), restored]); draw(); } } else if (action === "clear") { ink.set(key(), []); draw(); } else if (target.dataset.inkColor) { inkColor = target.dataset.inkColor; ui.querySelectorAll<HTMLElement>("[data-ink-color]").forEach((item) => item.classList.toggle("is-selected", item.dataset.inkColor === inkColor)); } else if (target.dataset.theme) { const preference = saved(); preference.theme = target.dataset.theme; saveStored(preference); ui.querySelectorAll<HTMLElement>("[data-theme]").forEach((item) => { const selected = item.dataset.theme === preference.theme; item.classList.toggle("is-selected", selected); item.setAttribute("aria-pressed", String(selected)); }); apply(); } else if (target.dataset.split && !applyingSplit) { applyingSplit = true; target.setAttribute("aria-pressed", "true"); target.classList.add("is-applying"); setSplitCookie(target.dataset.split as SplitPolicy); const url = new URL(location.href); url.searchParams.set("split", target.dataset.split); location.assign(url.toString()); } wake(); });
    ui.querySelectorAll<HTMLInputElement | HTMLSelectElement>("[data-setting]").forEach((input) => input.addEventListener("input", () => { const setting = input.dataset.setting!; if (setting === "inkWidth") { inkWidth = Number(input.value); return; } const preference = saved(); const value: string | number | boolean = input instanceof HTMLInputElement && input.type === "checkbox" ? input.checked : setting === "textScale" ? Number(input.value) : input.value; if (setting === "customRatio" && value && !ratio(String(value))) { input.setCustomValidity("Use width:height or a decimal ratio"); return; } input.setCustomValidity(""); (preference as Record<string, string | number | boolean>)[setting] = value; saveStored(preference); if (setting === "textScale") ui.querySelector<HTMLOutputElement>("[data-output=textScale]")!.textContent = `${value}%`; if (setting === "aspect") ui.querySelector<HTMLElement>(".slides-custom-ratio")!.hidden = value !== "custom"; apply(); }));
    ui.querySelector<HTMLInputElement>("[data-action=search]")?.addEventListener("input", (event) => { const query = (event.target as HTMLInputElement).value.toLowerCase(); picker.querySelectorAll<HTMLElement>("[data-search]").forEach((item) => item.hidden = !item.dataset.search!.toLowerCase().includes(query)); });
    canvas.addEventListener("pointerdown", (event) => { if (tool !== "pen") return; drawing = true; canvas.setPointerCapture(event.pointerId); stroke = { color: inkColor, width: inkWidth, points: [{ x: event.clientX / innerWidth, y: event.clientY / innerHeight }] }; ink.set(key(), [...strokes(), stroke]); redo.delete(key()); draw(); event.preventDefault(); }); canvas.addEventListener("pointermove", (event) => { if (!drawing || !stroke) return; stroke.points.push({ x: event.clientX / innerWidth, y: event.clientY / innerHeight }); draw(); }); canvas.addEventListener("pointerup", () => { drawing = false; stroke = null; });
    revealElement.addEventListener("pointermove", (event) => { wake(); if (tool === "laser") { laser.style.left = `${event.clientX}px`; laser.style.top = `${event.clientY}px`; laser.classList.add("is-visible"); } if (tool === "magnify" && magnified) { document.documentElement.style.setProperty("--slides-zoom-x", `${event.clientX}px`); document.documentElement.style.setProperty("--slides-zoom-y", `${event.clientY}px`); } }); revealElement.addEventListener("pointerdown", (event) => { if (!ui.contains(event.target as Node) && activePanel) panelClose(); if (tool === "magnify") { if (magnified) { setTool(null); return; } magnified = true; document.documentElement.style.setProperty("--slides-zoom-x", `${event.clientX}px`); document.documentElement.style.setProperty("--slides-zoom-y", `${event.clientY}px`); document.body.classList.add("slides-magnified"); event.preventDefault(); } });
    const scheduleApply = (): void => { clearTimeout(resizeTimer); resizeTimer = window.setTimeout(apply, 180); };
    deck.on("slidechanged", updateNavigation); window.addEventListener("resize", scheduleApply); revealElement.querySelectorAll("img,video,iframe").forEach((media) => media.addEventListener("load", scheduleApply)); window.setTimeout(scheduleApply, 500); document.addEventListener("pointermove", wake, { passive: true }); document.addEventListener("keydown", (event) => { if (event.key === "Escape") { if (activePanel) panelClose(); else if (tool) setTool(null); return; } if (event.target instanceof HTMLInputElement || event.target instanceof HTMLSelectElement) return; if (event.key === "?") panelOpen("help", dock.querySelector("[data-action=help]")!); else if (event.key.toLowerCase() === "g") panelOpen("picker", dock.querySelector("[data-action=picker]")!); else if (event.key.toLowerCase() === "f") { if (document.fullscreenElement) void document.exitFullscreen(); else void document.documentElement.requestFullscreen?.().catch(() => say("Fullscreen is unavailable")); } else if (event.key.toLowerCase() === "l") setTool("laser"); else if (event.key.toLowerCase() === "z") setTool("magnify"); else if (event.key.toLowerCase() === "d") setTool("pen"); else if (event.key.toLowerCase() === "b") deck.togglePause(); });
  });
});
